"""Claude Code 风格的最小通用 Agent Runtime。"""

from osc_agent.runtime.context import ContextProjection, SessionTranscript
from osc_agent.runtime.models import (
    Allow,
    AssistantDelta,
    AssistantMessageCompleted,
    Ask,
    Blocked,
    Cancelled,
    Complete,
    CapabilityScope,
    ContextUpdate,
    ContinueAfterCompact,
    ContinueAfterRecovery,
    ContinueWithTools,
    ContractModel,
    Deny,
    Failed,
    FrozenContractModel,
    PermissionDecision,
    QueryConfig,
    QueryParams,
    QueryState,
    RuntimeEvent,
    RuntimeMessage,
    ToolExecutionUpdate,
    ToolError,
    ToolResult,
    ToolUseContext,
    Transition,
)

__all__ = [
    "Allow",
    "AssistantDelta",
    "AssistantMessageCompleted",
    "Ask",
    "Blocked",
    "Cancelled",
    "Complete",
    "ContextProjection",
    "CapabilityScope",
    "ContextUpdate",
    "ContinueAfterCompact",
    "ContinueAfterRecovery",
    "ContinueWithTools",
    "ContractModel",
    "Deny",
    "Failed",
    "FrozenContractModel",
    "PermissionDecision",
    "QueryConfig",
    "QueryParams",
    "QueryState",
    "RuntimeEvent",
    "RuntimeMessage",
    "SessionTranscript",
    "ToolExecutionUpdate",
    "ToolError",
    "ToolResult",
    "ToolUseContext",
    "Transition",
]
